linters:
  enable:
  - bodyclose
  - deadcode
  - depguard
  - dogsled
  - dupl
  - errcheck
  - gochecknoglobals
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godot
  - godox
  - gofmt
  - goimports
  - golint
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - ineffassign
  - lll
  - misspell
  - nakedret
  - prealloc
  - rowserrcheck
  - staticcheck
  - structcheck
  - stylecheck
  - thelper
  - typecheck
  - unconvert
  - unparam
  - unused
  - varcheck
  - whitespace
  disable:
  - funlen
  - gomnd
  - nestif
  - testpackage
  - wsl

linters-settings:
  goimports:
    local-prefixes: github.com/twpayne/go-vfs

issues:
  exclude-rules:
  - linters:
    - scopelint
    path: "_test\\.go"