on:
  push:
    branches:
    - master
    tags:
    - 'v*'
  pull_request:
name: go-vfs
jobs:
  go-vfs:
    name: Test
    strategy:
      matrix:
        go-version:
        - "1.16"
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Go test
      run: go test ./...
    - name: Check formatting
      if: matrix.os == 'ubuntu-latest'
      run: |
        make format
        git diff --exit-code
  # FIXME re-enable lint
  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Lint
  #       uses: golangci/golangci-lint-action@v2
  #       with:
  #         version: v1.37.0
